name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-on-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.BACKEND_URL }}" > .env
          echo "NEXT_PUBLIC_FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env

      - name: SSH into VPS, Push Code, and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 9011
          script: |
            # Create the /root/front directory if not exists
            cd  /root/front

            # Copy the source code to /root/front
            scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/root/front

            # Change to /root directory
            cd /root

            # Build Docker image and deploy
            docker-compose -f docker-compose.yml up -d --build
